import 'package:hive/hive.dart';

part 'types_of_amount.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 1) // Assign a unique typeId for this class
class TypesOfAmount {
  @HiveField(0)
  final double selectOptionAmount;

  @HiveField(1)
  final double expenseAmount;

  @HiveField(2)
  final String remarks;

  @HiveField(3)
  final double incomeAmount;

  // Constructor for TypesOfAmount
  TypesOfAmount({
    required this.selectOptionAmount,
    required this.expenseAmount,
    required this.remarks,
    required this.incomeAmount,
  });
}
